package ru.cse.APILk.Service1c;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2017-09-20T17:30:06.930+03:00
 * Generated source version: 3.1.7
 * 
 */
@WebService(targetNamespace = "http://www.cse-cargo.ru/client", name = "SorterExchangePortType")
@XmlSeeAlso({ObjectFactory.class})
public interface SorterExchangePortType {

    @WebMethod(operationName = "GetDataPushExit", action = "http://www.cse-cargo.ru/client#SorterExchange:GetDataPushExit")
    @RequestWrapper(localName = "GetDataPushExit", targetNamespace = "http://www.cse-cargo.ru/client", className = "ru.cse.APILk.Service1c.GetDataPushExit")
    @ResponseWrapper(localName = "GetDataPushExitResponse", targetNamespace = "http://www.cse-cargo.ru/client", className = "ru.cse.APILk.Service1c.GetDataPushExitResponse")
    @WebResult(name = "return", targetNamespace = "http://www.cse-cargo.ru/client")
    public java.lang.String getDataPushExit(
        @WebParam(name = "InParametrs", targetNamespace = "http://www.cse-cargo.ru/client")
        java.lang.String inParametrs,
        @WebParam(name = "InputStruc", targetNamespace = "http://www.cse-cargo.ru/client")
        ru.cse.APILk.Service1c.Array inputStruc,
        @WebParam(mode = WebParam.Mode.OUT, name = "OutParametrs", targetNamespace = "http://www.cse-cargo.ru/client")
        javax.xml.ws.Holder<java.lang.String> outParametrs
    );
}
