package ru.cse.APILk.Service1c;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2017-09-15T21:50:54.963+03:00
 * Generated source version: 3.1.7
 * 
 */
@WebServiceClient(name = "WebServicesNewCSE", 
                  wsdlLocation = "http://web.cse.ru/cse82_reg/ws/WebServicesNewCSE?wsdl",
                  targetNamespace = "http://www.cse-cargo.ru/client") 
public class WebServicesNewCSE extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.cse-cargo.ru/client", "WebServicesNewCSE");
    public final static QName WebServicesNewCSESoap = new QName("http://www.cse-cargo.ru/client", "WebServicesNewCSESoap");
    public final static QName WebServicesNewCSESoap12 = new QName("http://www.cse-cargo.ru/client", "WebServicesNewCSESoap12");
    static {
        URL url = null;
        try {
            url = new URL("http://web.cse.ru/cse82_reg/ws/WebServicesNewCSE?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WebServicesNewCSE.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://web.cse.ru/cse82_reg/ws/WebServicesNewCSE?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public WebServicesNewCSE(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WebServicesNewCSE(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebServicesNewCSE() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public WebServicesNewCSE(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public WebServicesNewCSE(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public WebServicesNewCSE(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     * 
     * 				
     * 			
     *
     * @return
     *     returns WebServicesNewCSEPortType
     */
    @WebEndpoint(name = "WebServicesNewCSESoap")
    public WebServicesNewCSEPortType getWebServicesNewCSESoap() {
        return super.getPort(WebServicesNewCSESoap, WebServicesNewCSEPortType.class);
    }

    /**
     * 
     * 				
     * 			
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebServicesNewCSEPortType
     */
    @WebEndpoint(name = "WebServicesNewCSESoap")
    public WebServicesNewCSEPortType getWebServicesNewCSESoap(WebServiceFeature... features) {
        return super.getPort(WebServicesNewCSESoap, WebServicesNewCSEPortType.class, features);
    }


    /**
     *
     * @return
     *     returns WebServicesNewCSEPortType
     */
    @WebEndpoint(name = "WebServicesNewCSESoap12")
    public WebServicesNewCSEPortType getWebServicesNewCSESoap12() {
        return super.getPort(WebServicesNewCSESoap12, WebServicesNewCSEPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebServicesNewCSEPortType
     */
    @WebEndpoint(name = "WebServicesNewCSESoap12")
    public WebServicesNewCSEPortType getWebServicesNewCSESoap12(WebServiceFeature... features) {
        return super.getPort(WebServicesNewCSESoap12, WebServicesNewCSEPortType.class, features);
    }

}
